---
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-perf-db-config
data:
  # This is localhost because we proxy postgres through a sidecar.
  PL_POSTGRES_HOSTNAME: localhost
  PL_POSTGRES_PORT: "5432"
  PL_POSTGRES_DB: px_perf
  PL_POSTGRES_INSTANCE: pl-pixies:us-west1:px-perf
