---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-reader
  namespace: px-perf
spec:
  selector:
    matchLabels:
      name: db-reader
  template:
    metadata:
      labels:
        name: db-reader
    spec:
      containers:
      - image: postgres:14-alpine
        imagePullPolicy: IfNotPresent
        name: psql
        command: ["bash"]
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                  "-instances=$(PL_POSTGRES_INSTANCE)=tcp:$(PL_POSTGRES_PORT)",
                  "-ip_address_types=PRIVATE",
                  "-credential_file=/secrets/cloudsql/db_service_account.json"]
        envFrom:
        - configMapRef:
            name: px-perf-db-config
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
        - name: px-perf-db-secrets
          mountPath: /secrets/cloudsql
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: px-perf-db-secrets
        secret:
          secretName: px-perf-db-secrets
