---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc
spec:
  template:
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                  "-instances=$(PL_POSTGRES_INSTANCE)=tcp:$(PL_POSTGRES_PORT)",
                  "-ip_address_types=PRIVATE",
                  "-credential_file=/secrets/cloudsql/db_service_account.json"]
        envFrom:
        - configMapRef:
            name: px-perf-db-config
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
        - name: px-perf-db-secrets
          mountPath: /secrets/cloudsql
          readOnly: true
      # [END proxy_container]
      volumes:
      - name: px-perf-db-secrets
        secret:
          secretName: px-perf-db-secrets
