---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: px-perf
namespace: px-perf
resources:
- db_config.yaml
- bq_config.yaml
- tls_config.yaml
- kuberesolver_role.yaml
- db_reader_role.yaml
- db_reader.yaml
- coordinator_deployment.yaml
- coordinator_service.yaml
- clustermgr_deployment.yaml
- clustermgr_service.yaml
- builder_deployment.yaml
- builder_service.yaml
- runner_deployment.yaml
- runner_service.yaml
patches:
- path: db_sidecar.yaml
  target:
    kind: Deployment
    labelSelector: db=pgsql
