---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-server
spec:
  selector:
    matchLabels:
      name: runner-server
  template:
    metadata:
      labels:
        name: runner-server
    spec:
      containers:
      - name: runner-server
        imagePullPolicy: IfNotPresent
        image: gcr.io/pixie-oss/pixie-dev/px-perf/runner_server_image
        ports:
        - containerPort: 50200
          name: http2
        - containerPort: 50201
          name: metrics-http
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50200
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50200
        envFrom:
        - configMapRef:
            name: px-perf-bq-config
        - configMapRef:
            name: px-perf-tls-config
        - configMapRef:
            name: px-perf-service-config
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: bq-access-sa
          mountPath: /creds
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
      - name: bq-access-sa
        secret:
          secretName: px-perf-bq-secrets
