---
apiVersion: v1
kind: Service
metadata:
  name: runner-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 50200
    protocol: TCP
    targetPort: 50200
    name: tcp-http2
  selector:
    name: runner-server
