---
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-perf-service-config
data:
  PL_COORDINATOR_SERVICE: kubernetes:///coordinator-service.px-perf:50000
  PL_CLUSTERMGR_SERVICE: kubernetes:///clustermgr-service.px-perf:50100
  PL_RUNNER_SERVICE: kubernetes:///runner-service.px-perf:50200
  PL_BUILDER_SERVICE: kubernetes:///builder-service.px-perf:50300
