---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/px-perf/coordinator_server_image
    context: .
    bazel:
      target: //src/e2e_test/perf_tool/backend/coordinator:coordinator_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/px-perf/clustermgr_server_image
    context: .
    bazel:
      target: //src/e2e_test/perf_tool/backend/clustermgr:clustermgr_server_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - src/e2e_test/perf_tool/backend/k8s
